#!/usr/bin/env bash
# This script displays information about subdomains

info_display () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  info_display "$1" "www"
  info_display "$1" "lb-01"
  info_display "$1" "web-01"
  info_display "$1" "web-02"
elif [ "$#" == 2 ]
then
  info_display "$1" "$2"
fi
