#!/usr/bin/env bash
# Installs Nginx on Server and handles redirection
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
