#!/usr/bin/env bash
# Installs and configures haproxy load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 502-web-01 35.196.247.36:80 check
    server 502-web-02 35.170.81.242:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

