#!/usr/bin/env bash
# Configures Nginx listening port to 80 and kills nginx process
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
