#!/usr/bin/env bash
# This script manages the manage_my_process script

args=("$@")
if [ "${#args[@]}" -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
else
	if [ "$1" = "start" ]; then
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
	elif [ "$1" = "stop" ]; then
		kill -SIGKILL "$(cat /var/run/my_process.pid)" 
		rm -f /var/run/my_process.pid
		echo "manage_my_process stopped"
	elif [ "$1" = "restart" ]; then
		kill -SIGKILL "$(cat /var/run/my_process.pid)" 
		rm -f /var/run/my_process.pid
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
	fi
fi
