#!/usr/bin/env bash
# This script displays "Best School" 8 times
#+ Displays "bad luck" on the 4th iteration
#+ Displays "good luck" on the 8th iteration
counter=0
while [ $counter -lt 10 ]; do
	if [ $counter -eq 3 ]
	then
		echo "bad luck"
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( counter+=1 ))
done 
