#!/usr/bin/env bash
# Fixes server so that nginx runs under username 'nginx'
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
